In [7]:
import pandas as pd
col = ['image_id', 'attribute_id', 'isPresent']
data = pd.read_csv('test_label_attributes.txt', header = None, sep = " ", names = col)
data.head(10)

   image_id  attribute_id  isPresent
0         1             1          0
1         1             2          0
2         1             3          0
3         1             4          0
4         1             5          1
5         1             6          0
6         1             7          0
7         1             8          0
8         1             9          0
9         1            10          0

In [11]:
col1 = ['attribute_id', 'attribute_name']
attr = pd.read_csv('attributes.txt', header =None, sep =' ',  names = col1)
attr.head(10)

   attribute_id                       attribute_name
0             1  has_bill_shape::curved_(up_or_down)
1             2               has_bill_shape::dagger
2             3               has_bill_shape::hooked
3             4               has_bill_shape::needle
4             5       has_bill_shape::hooked_seabird
5             6            has_bill_shape::spatulate
6             7          has_bill_shape::all-purpose
7             8                 has_bill_shape::cone
8             9          has_bill_shape::specialized
9            10                 has_wing_color::blue

In [15]:
joined = data.join(attr.set_index('attribute_id'), on='attribute_id', validate='m:1')
columns_titles = ["image_id","attribute_id", "attribute_name", "isPresent"]
joined=joined.reindex(columns=columns_titles)
joined

,image_id,attribute_id,attribute_name,isPresent
0,1,1,has_bill_shape::curved_(up_or_down),0
1,1,2,has_bill_shape::dagger,0
2,1,3,has_bill_shape::hooked,0
3,1,4,has_bill_shape::needle,0
4,1,5,has_bill_shape::hooked_seabird,1
...,...,...,...,...
1807723,11788,308,has_crown_color::buff,1
1807724,11788,309,has_wing_pattern::solid,0
1807725,11788,310,has_wing_pattern::spotted,0
1807726,11788,311,has_wing_pattern::striped,0
1807727,11788,312,has_wing_pattern::multi-colored,1